### ISSUE TITLE
Countly initialization crash: disableLocationInternal

### ISSUE THREAD

**Issue by enginegl** [Countly/countly-sdk-android#128] opened 2021-02-11 14:13 UTC
Application code:
```kotlin
fun initCountly(application: Application) {
    Countly.sharedInstance().init(
        CountlyConfig(application, <>, <>).apply {
            setDisableLocation()
        }
    )
}
```

### Expected Behavior
Initialization should complete successfully.

### Current Behavior
Crash on start:
```
Caused by: java.lang.IllegalStateException: context has not been set
  at ly.count.android.sdk.ConnectionQueue.checkInternalState(ConnectionQueue.java:139)
  at ly.count.android.sdk.ConnectionQueue.sendLocation(ConnectionQueue.java:334)
  at ly.count.android.sdk.ModuleLocation.disableLocationInternal(ModuleLocation.java:77)
  at ly.count.android.sdk.ModuleLocation.<init>(ModuleLocation.java:30)
  at ly.count.android.sdk.Countly.init(Countly.java:531)
```

### Possible Solution
Init ConnectionQueue context before `sendLocation` method call.

### Your Environment

* Countly Android SDK version: **ly.count.android:sdk:20.11.4**
* Your Android version: **any version**
* Your device: **any device**
* Any changes you have made to this SDK: **no changes**

**Comment by ArtursKadikis** [comment] 2021-02-11 14:30
Hello, thanks for reporting this. This was already a know issue. A current workaround is to call "setContext()" on the config object and provide a valid context before initialising.

**Comment by watzkuh** [comment] 2021-02-22 09:54
Hi, I also reproducibly run into the same exception with version 20.11.5.
I tried to follow your suggestion @ArtursKadikis but setting the context explicitly on the config object does not have any effect, the context in `ConnectionQueue` is still null during the initialization of `ModuleLocation`.

Application code:
        
```
val config = CountlyConfig(application, MY_KEY, MY_URL).apply {
    setContext(applicationContext)
    setDisableLocation()
}
Countly.sharedInstance().init(config)
```
The only currently valid solution seems to be to disable location tracking after the initialization

**Comment by ArtursKadikis** [comment] 2021-02-22 10:07
Thanks for reporting this. There was some other related to disabling location during init. That is fixed now and I'll publish a new release later today (20.11.6).

**Comment by ArtursKadikis** [comment] 2021-02-23 00:20
I just published the new release. Let me know if it fixes the issue for you.

**Comment by watzkuh** [comment] 2021-02-23 10:52
I no longer encounter the issue with release 20.11.6

**Closed** 2021-02-23 13:06 UTC
