### ISSUE TITLE
21.11.0 release broken due to internal API and no documentation

### ISSUE THREAD

**Issue by polivmi1** [Countly/countly-sdk-android#139] opened 2022-05-12 08:44 UTC
Countly.sharedInstance().deviceId().getID() and other new methods suggested instead of the deprecated ones are not accessible because of non-public class. This breaks in the latest 21.11.0 release

Cannot access 'ModuleDeviceId': it is package-private in 'ly.count.android.sdk'

Also the documentation at https://support.count.ly/hc/en-us/articles/360037754031-Android#user-profiles still mentions the old API

**Comment by ArtursKadikis** [comment] 2022-05-12 09:54
Hello. That's kinda weird. I can't reproduce the "not accessible" issue. Even when creating a new app with a random package name. It wasn't also showing up in other tests. What is your current setup and platform?

**Comment by polivmi1** [comment] 2022-05-12 10:13
Latest stable AS, Kotlin, Android. See https://ibb.co/CwxTsq2 
ModuleDeviceId is declared as a private class

`
class ModuleDeviceId extends ModuleBase implements OpenUDIDProvider, DeviceIdProvider {`

**Comment by ArtursKadikis** [comment] 2022-05-12 10:28
Ah, I see, it was the Kotlin side that was having issues. When using this with Java, it was compiling without any errors or warnings, even when using those new calls.

We'll release a .1 release that would fix the issue.

**Comment by ArtursKadikis** [comment] 2022-05-12 17:13
Hello just released 21.11.1 with a fix for this.

**Closed by ArtursKadikis** 2022-05-12 17:13 UTC
